# Basic Python

## 1. Split this string

In [5]:
s = "Hi there Sam!"

In [6]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742

In [3]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
array=np.zeros(10)

print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
array=np.ones(10)*5

print(array)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [11]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [20]:
a = np.array([1,2,3])
b = np.array([4, 5, 6])


In [23]:
print (np.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd


In [25]:
data = {
  "Teams": ["Team1", "Team2", "Team3"],
  "Score": [50, 40, 45]
}
 
df = pd.DataFrame(data)
 
print(df) 

   Teams  Score
0  Team1     50
1  Team2     40
2  Team3     45


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [28]:
d = pd.date_range(start='1/1/2023', end='10/2/2023', freq='MS')
print(d)

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01'],
              dtype='datetime64[ns]', freq='MS')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [33]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [36]:
df = pd.DataFrame(lists, columns =['S.No', 'Name', 'Age'],
                                           dtype = int) 
print(df)

   S.No Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Could not cast to int64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)
